# Generated by Django 3.2.3 on 2021-05-26 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pjapp', '0007_todo_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='title',
            field=models.CharField(default='Заметка <property object at 0x000001D4A862B3B0>', max_length=64, verbose_name='Заголовок'),
        ),
    ]
